modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

# Misc packages
  - type: dnf
    install:
      packages:
        - distrobox
        - zsh

# Ublue packages
  - type: dnf
    repos:
      cleanup: true
      copr: 
        - ublue-os/packages
    install:
      install-weak-deps: false
      packages:
        - just 
        - ublue-os-udev-rules
        - ublue-os-signing
        - ublue-os-luks
        - ublue-os-just
        - uupd

  - type: systemd 
    system: 
      enabled:
        - uupd.timer 
      disabled:
        - rpm-ostreed-automatic.timer

# Theming/Fonts
  - type: fonts
    fonts:
      #google-fonts:
      #  - Open Sans
      #  - Noto Color Emoji
      nerd-fonts:
        - SourceCodePro
  - type: dnf
    install:
      packages:
        #- open-sans-fonts
        - google-noto-emoji-color-fonts
        - fontawesome-fonts-all
        - google-noto-sans-vf-fonts 
        - google-noto-serif-vf-fonts 
        - google-noto-sans-cjk-vf-fonts 
        - google-noto-serif-cjk-vf-fonts
        #- gnome-themes-extra
        - gnome-icon-theme
        - paper-icon-theme
        - breeze-icon-theme 
        - papirus-icon-theme
 
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
  #      # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.World.PikaBackup/x86_64/stable
          - io.github.kolunmi.Bazaar/x86_64/stable
          - org.libreoffice.LibreOffice/x86_64/stable
      - scope: user # Also add Flathub user repo, but no user packages
  
  - type: brew
    nofile-limits: true
    brew-analytics: true
    direct-pull: false 
    auto-upgrade: false # uupd should update this 

  - type: os-release
    properties:
      ID: fedora 
      ID_LIKE: octo_train 
      NAME: OctoTrain
      PRETTY_NAME: OctoTrain (BlueBuild)
